version: '3'

services:

  server:
    build: ./server1
    expose:
      - 5000
    environment:
      APP_SERVER_PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/src/app/fr-shohin-admin-server/src
    command: npm run start


  client:
    build: ./client
    environment:
      REACT_APP_PORT: 3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/srv/app/fr-shohin-admin-client/src
      - ./client/public:/srv/app/fr-shohin-admin-client/public
    links:
      - server
    command: npm run start
